static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    metadata:
      filter_metadata:
        envoy.filters.http.lua: 
          listener: "listener metadata"
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - name: "default"
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua: 
                      route: 
                       - "route metadata1"
                       - "route metadata2"
                match:
                  prefix: "/"
                route:
                  cluster: server
          http_filters:
          - name: envoy.filters.http.lua
            typed_config: 
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                -- Called on the request path.
                function envoy_on_request(request_handle)
                  request_handle:logInfo("hello world")
                  local route_metadata = request_handle:metadata():get("route") or {}
                      for i,v in ipairs(route_metadata) do
                          request_handle:logInfo(v)
                      end
                  request_handle:logInfo(request_handle:metadata():get("listener"))
                end
                -- Called on the response path.
                function envoy_on_response(response_handle)
                  -- Do something.
                end
          - name: envoy.filters.http.router
            typed_config: {}
  clusters:
  - name: server
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: server
                port_value: 1500
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001