resources:
  - "@type": "type.googleapis.com/envoy.api.v2.auth.Secret"
    tls_certificate:
      certificate_chain:
        filename: /etc/certs/servercert.pem
      private_key:
        filename: /etc/certs/serverkey.pem
